# NUMPY PRACTICE

# Basic Declaration

# All : https://numpy.org/doc/stable/index.html

In [15]:
import numpy as np #import numpy in python

In [2]:
a = np.array([1,2,3,4]) # Declar 1D array
type(a) 

numpy.ndarray

In [3]:
a.shape  #how many row and column,for 1D it returns only column

(4,)

In [5]:
b = np.array([[1.0,2.0,4.0],[6.0,2.4,5.3]])  #Declar 2D array
b.shape #how many row and column

(2, 3)

In [16]:
b.ndim # Returns the dimension

2

In [9]:
a.dtype  #what is the datatype it is


dtype('int32')

In [10]:
b.dtype   #what is the datatype it is

dtype('float64')

In [11]:
c = np.array([4,5,6,8],dtype="int16") #You may define datatype

In [12]:
c.dtype   #what is the datatype it is

dtype('int16')

In [13]:
c.itemsize   #how many memory use for the datatype

2

In [14]:
c.nbytes   #return total memory that use in the array

8

# Indexing, Accessing

In [20]:
ar = np.array([[5,4,3,5,2,7,9],[2,3,5,6,3,2,6],[4,5,3,6,2,6,8]]) #Declar an 2D array
ar

array([[5, 4, 3, 5, 2, 7, 9],
       [2, 3, 5, 6, 3, 2, 6],
       [4, 5, 3, 6, 2, 6, 8]])

In [23]:
ar[2,4]  #get a specific element in ar[r,c]

2

In [28]:
#Get a specific row
np.array(ar[1,:])


array([2, 3, 5, 6, 3, 2, 6])

In [25]:
#Get a specific column
ar[:,3]

array([5, 6, 6])

In [29]:
ar[0,0:4:2]  #(row/column,startindex:endindex,stepsize) 

array([5, 3])

In [30]:
ar[:,3] =7   # Update a column in a specific value
ar

array([[5, 4, 3, 7, 2, 7, 9],
       [2, 3, 5, 7, 3, 2, 6],
       [4, 5, 3, 7, 2, 6, 8]])

In [31]:
u = [2,3,1]  #Update samething with a list
ar[:,3]=u
ar

array([[5, 4, 3, 2, 2, 7, 9],
       [2, 3, 5, 3, 3, 2, 6],
       [4, 5, 3, 1, 2, 6, 8]])

In [32]:
ar[0,:]=1  #update a row into a value
ar

array([[1, 1, 1, 1, 1, 1, 1],
       [2, 3, 5, 3, 3, 2, 6],
       [4, 5, 3, 1, 2, 6, 8]])

In [33]:
w = [5,4,3,2,2,7,9]  #update samething with a list
ar[0,:]=w
ar

array([[5, 4, 3, 2, 2, 7, 9],
       [2, 3, 5, 3, 3, 2, 6],
       [4, 5, 3, 1, 2, 6, 8]])

In [48]:
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[2,3,4],[5,6,4],[1,6,4]]])
#Declar 3D array
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[2, 3, 4],
        [5, 6, 4],
        [1, 6, 4]]])

In [49]:
threeD[0,1,1]  #[index of 2DArray,r,c]

5

In [37]:
threeD.ndim

3

In [41]:
threeD.shape

(2, 3, 3)

In [50]:
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[2, 3, 4],
        [5, 6, 4],
        [1, 6, 4]]])

In [51]:
threeD [0,1,1]=9


In [52]:
threeD

array([[[1, 2, 3],
        [4, 9, 6],
        [7, 8, 9]],

       [[2, 3, 4],
        [5, 6, 4],
        [1, 6, 4]]])

In [55]:
threeD[1,:,:] = [[5,6,4],[3,4,5],[1,9,6]]

In [56]:
threeD

array([[[1, 2, 3],
        [4, 9, 6],
        [7, 8, 9]],

       [[5, 6, 4],
        [3, 4, 5],
        [1, 9, 6]]])

In [57]:
threeD[0,1,0:]=[5,5,5]

In [58]:
threeD

array([[[1, 2, 3],
        [5, 5, 5],
        [7, 8, 9]],

       [[5, 6, 4],
        [3, 4, 5],
        [1, 9, 6]]])

# initialize different types of arrays


In [75]:
np.zeros((5,2,3),dtype="int32")  #((shape),dtype,)


array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [85]:
np.full((2,2,2),100.0)   #Fill array with a specific value in 3D

array([[[100., 100.],
        [100., 100.]],

       [[100., 100.],
        [100., 100.]]])

In [83]:
np.full(2,100)  #Fill array with a specific value in 1D

array([100, 100])

In [89]:
np.full((2,2),'c')  #Fill array with a specific value in 2D

array([['c', 'c'],
       ['c', 'c']], dtype='<U1')

In [96]:
threeD_er_soman = np.full_like(threeD,100) #fill with a specific value as another numpy array shape

In [97]:
threeD

array([[[1, 2, 3],
        [5, 5, 5],
        [7, 8, 9]],

       [[5, 6, 4],
        [3, 4, 5],
        [1, 9, 6]]])

In [98]:
threeD_er_soman

array([[[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]]])

In [104]:
np.random.rand(2,2,2)  #3D random value generate

array([[[0.24003846, 0.24469273],
        [0.11432966, 0.9017632 ]],

       [[0.20041576, 0.12357536],
        [0.55105885, 0.66515281]]])

In [105]:
np.random.rand(2,2)  #2D random value generate

array([[0.16432493, 0.77771802],
       [0.17176153, 0.33809102]])

In [106]:
np.random.rand(2)  #1D random value generate

array([0.52934241, 0.3382018 ])

In [107]:
np.random.random_sample(threeD.shape)  # #fill with random value as another numpy array shape

array([[[0.08920384, 0.24088763, 0.70097806],
        [0.74245192, 0.90264657, 0.85442776],
        [0.38595999, 0.07739923, 0.35949167]],

       [[0.17246833, 0.52333717, 0.84230024],
        [0.56137654, 0.226817  , 0.01896585],
        [0.609655  , 0.3240517 , 0.51521095]]])

In [112]:
np.random.randint(0,100,(2,2))   #low,high,dimension 

array([[51, 56],
       [81, 45]])

In [117]:
np.identity(5,dtype="int32")   #to get identity matrix n x n

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [128]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)  #Repeat an array
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [131]:
v = np.ones((5,2,3),dtype="int32")  #((shape),dtype,)
v

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

# Mathematics

In [133]:
ab = np.array([9,7,8,5,4,6,3,2,2,1,0,8])
ab

array([9, 7, 8, 5, 4, 6, 3, 2, 2, 1, 0, 8])

In [134]:
ab*2

array([18, 14, 16, 10,  8, 12,  6,  4,  4,  2,  0, 16])

In [135]:
ab%2

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int32)

In [137]:
ab/2

array([4.5, 3.5, 4. , 2.5, 2. , 3. , 1.5, 1. , 1. , 0.5, 0. , 4. ])

In [138]:
ab-2

array([ 7,  5,  6,  3,  2,  4,  1,  0,  0, -1, -2,  6])

In [139]:
ab+2

array([11,  9, 10,  7,  6,  8,  5,  4,  4,  3,  2, 10])

In [140]:
np.cos(ab)

array([-0.91113026,  0.75390225, -0.14550003,  0.28366219, -0.65364362,
        0.96017029, -0.9899925 , -0.41614684, -0.41614684,  0.54030231,
        1.        , -0.14550003])

In [144]:
np.sin(ab)


array([ 0.41211849,  0.6569866 ,  0.98935825, -0.95892427, -0.7568025 ,
       -0.2794155 ,  0.14112001,  0.90929743,  0.90929743,  0.84147098,
        0.        ,  0.98935825])

In [145]:
np.tan(ab)

array([-0.45231566,  0.87144798, -6.79971146, -3.38051501,  1.15782128,
       -0.29100619, -0.14254654, -2.18503986, -2.18503986,  1.55740772,
        0.        , -6.79971146])

# Linar algebra 

In [150]:
x = np.ones((2,3))
y =np.full((3,2),2)


In [154]:
mul = np.matmul(x,y)   #Matrixx multipliccation
mul

array([[6., 6.],
       [6., 6.]])

In [158]:
c = np.identity(3)
np.linalg.det(c)   #get determinate of an identity matrix

1.0

In [162]:
bah = np.array([[2,1],[4,5]])
print(bah)
np.linalg.det(bah)     #get determinate of an matrix

[[2 1]
 [4 5]]


6.0

# Statistics

In [163]:
starts = np.array([[1,2,3],[4,5,6]])
starts

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
np.mean(starts) #Mean value of an matrix

3.5

In [165]:
np.min(starts)  #MIN VALUE

1

In [166]:
np.max(starts) #get max val

6

In [168]:
np.min(starts[1,:])  #min in a row

4

In [170]:
np.max(starts[:,1])  #max in a column

#we can get min,max,sum,mean of specif area in a matrix(just think and apply)

5

In [171]:
np.mean(starts[0:2,1:3])
#we can get min,max,sum,mean of specif area in a matrix(just think and apply)

4.0

# Recognizing arrays

In [6]:
before = np.array([[1,2,3],[4,5,6]])
print(before)


after = before.reshape((3,2))   #Reshape an array bt check it valid or not
print(after)

after =before.reshape((2,1,3))
print(after)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[[1 2 3]]

 [[4 5 6]]]


In [8]:
#Horizonal stack

st1 = np.array([1,2,3,4,5])
st2 = np.array([5,6,7,8,9])
np.hstack((st1,st2))

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [9]:
#vertically stack
np.vstack((st1,st2))

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

# Miscellaneous

## Load Data From file

In [21]:
file = np.genfromtxt('at.txt',delimiter=',')
file = file.astype('int32')
file

array([[  1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  12,  33, 455,   6,  66,  77,  51],
       [  1,   2,  24,  55,  66,  66,  77,   6],
       [  1,   2,  34,   5,   6,   6,   4,   3]])

## Boolean masking and advance indexing

In [23]:
file>15

array([[False, False, False, False, False, False, False, False],
       [False, False,  True,  True, False,  True,  True,  True],
       [False, False,  True,  True,  True,  True,  True, False],
       [False, False,  True, False, False, False, False, False]])

In [24]:
file[file>15]

array([ 33, 455,  66,  77,  51,  24,  55,  66,  66,  77,  34])

In [25]:
ax = np.array([9,8,7,6,0,5,4,3,2,1])
ax[[1,3,5,7,9]]

array([8, 6, 5, 3, 1])

In [26]:
ax[1:10:2]

array([8, 6, 5, 3, 1])

In [27]:
np.any(file>15, axis=0)

array([False, False,  True,  True,  True,  True,  True,  True])

In [28]:
np.any(file>15, axis=1)

array([False,  True,  True,  True])

In [29]:
file[1:3,2:5]

array([[ 33, 455,   6],
       [ 24,  55,  66]])

# Links with more information! 

NumPy vs Lists:
https://jakevdp.github.io/blog/2014/05/09/why-python-is-slow/

Indexing: 
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html

Array Creation Routines:
https://numpy.org/doc/stable/reference/routines.array-creation.html

Math Routines Docs:
https://numpy.org/doc/stable/reference/routines.math.html

Linear Algebra Docs:
https://numpy.org/doc/stable/reference/routines.linalg.html
